# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9d89c6b3dc17c6704b501a9cb3f807f6e8bd1632483f5e7e75e21d95f558c4dc60af8ee7829f45f55544160910a4083e85d620bf50ed8f40b446ffa74a9cee5

test:
  secret_key_base: ca1790dcd99a9cb4248ae3616f55eb77de03a108cc43fdfd33f1328afa0c6c72cf0cdfe060ab45eb2b8ae3b24e50c33a9c9913b19d8380693b02efd87c9f62ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
